const translations = {
    id: {
        nav_home:       "Beranda",
        nav_about:      "Tentang",
        nav_projects:   "Proyek",
        nav_articles:   "Artikel",
        nav_contact:    "Kontak",
        hero_badge:     "Merangkai Ide, Merangkul Transformasi",
        hero_role_prefix: "Seorang",
        hero_desc:      "Suka explorasi teknologi, ekonomi, dan hal-hal baru.",
        btn_projects:   "Lihat Proyek",
        btn_contact:    "Hubungi Saya",
        about_label:    "Tentang Saya",
        about_title:    `Halo, saya<span class="ta"> Muhammad Aklilul Hikam</span>`,
        about_p1:       `Saya mahasiswa <strong>Sistem Informasi Bisnis</strong> di Politeknik Negeri Malang, individu yang selalu penasaran dengan pertemuan antara teknologi dan strategi bisnis modern.`,
        about_p2:       "Perjalanan saya dimulai dari pengembangan web, lalu berkembang ke ekosistem Web3 dan Cryptocurrency. Berawal dari eksplorasi airdrop, saya menemukan minat mendalam pada teknologi blockchain dan bagaimana desentralisasi dapat mengubah masa depan ekonomi digital.",
        info_name:      "Nama Lengkap",
        info_loc:       "Lokasi",
        info_study:     "Studi",
        info_email:     "Email",
        abilities_title:"Abilities",
        ability_sleep:  "Tidur",
        ability_learn:  "Belajar Hal Baru",
        ability_idea:   "Mewujudkan Ide",
        ability_coffee: "Ngopi",
        ability_write:  "Nulis",
        projects_label: "Proyek",
        projects_title: "CASE STUDY",
        projects_subtitle:"Arsip kontribusi dan eksperimen digital",
        articles_label: "Tulisan",
        articles_title: `Apa yang <span class="ta">Saya Tulis</span>`,
        articles_subtitle:"Kumpulan tulisan dan opini tentang teknologi &amp; ekonomi",
        contact_hi:     "Say Hi!",
        contact_and:    " dan ceritakan tentang",
        contact_idea:   "idemu",
        contact_desc:   "Terbuka untuk diskusi Web3, Blockchain, atau peluang kolaborasi teknis lainnya.",
        form_name_label:"Nama",
        form_email_label:"Email",
        form_purpose_label:"Keperluan?",
        form_msg_label: "Pesan",
        form_name_ph:   "Halo...",
        form_email_ph:  "Balas ke mana?",
        form_purpose_ph:"Tulis keperluanmu disini",
        form_msg:       "Ceritakan idemu...",
        form_btn:       "Kirim pesan",
        form_sending:   "Mengirim...",
        form_sent:      "Terkirim",
        form_fail:      "Gagal Kirim",
        open_project:   "BUKA PROYEK",
        footer:         "© 2026 Muhammad Aklilul Hikam. All rights reserved.",
        roles:          ["Web3 Enthusiast", "Mahasiswa", "Penjelajah Teknologi", "Content Writer"]
    },
    en: {
        nav_home:       "Home",
        nav_about:      "About",
        nav_projects:   "Projects",
        nav_articles:   "Articles",
        nav_contact:    "Contact",
        hero_badge:     "Crafting Ideas, Embracing Transformation",
        hero_role_prefix: "A",
        hero_desc:      "Exploring technology, economics, and new things.",
        btn_projects:   "View Projects",
        btn_contact:    "Contact Me",
        about_label:    "About Me",
        about_title:    `Hi, I'm <span class="ta"> Muhammad Aklilul Hikam</span>`,
        about_p1:       `I'm a <strong>Business Information Systems</strong> student at State Polytechnic of Malang, always curious about the intersection of technology and modern business strategy.`,
        about_p2:       "My journey started with web development, then evolved into the Web3 and Cryptocurrency ecosystem. Starting from airdrop exploration, I discovered a deep interest in blockchain technology and how decentralization can reshape the future of the digital economy.",
        info_name:      "Full Name",
        info_loc:       "Location",
        info_study:     "Study",
        info_email:     "Email",
        abilities_title:"Abilities",
        ability_sleep:  "Sleeping",
        ability_learn:  "Learning New Things",
        ability_idea:   "Realizing Ideas",
        ability_coffee: "Drinking Coffee",
        ability_write:  "Writing",
        projects_label: "Projects",
        projects_title: "CASE STUDY",
        projects_subtitle:"Archive of digital contributions and experiments",
        articles_label: "Writing",
        articles_title: `What I <span class="ta">Write</span>`,
        articles_subtitle:"Collection of writings and opinions on technology &amp; economics",
        contact_hi:     "Say Hi!",
        contact_and:    " and tell me about",
        contact_idea:   "your idea",
        contact_desc:   "Open to discussions on Web3 development, Blockchain research, or other technical collaboration opportunities.",
        form_name_label:"Name",
        form_email_label:"Email",
        form_purpose_label:"Purpose?",
        form_msg_label: "Message",
        form_name_ph:   "Hello...",
        form_email_ph:  "Where can I reply?",
        form_purpose_ph:"Write your purpose here",
        form_msg:       "Tell me about your idea...",
        form_btn:       "Send me your message",
        form_sending:   "Sending...",
        form_sent:      "Sent",
        form_fail:      "Failed to Send",
        open_project:   "OPEN PROJECT",
        footer:         "© 2026 Muhammad Aklilul Hikam. All rights reserved.",
        roles:          ["Web3 Enthusiast", "Student", "Tech Explorer", "Content Writer"]
    }
};

const portfolioData = [
  {
    id: 1,
    title: "BarbarianX DAO",
    category: "DAO Governance",
    category_en: "DAO Governance",
    description: "Platform komunitas BarbarianX DAO",
    description_en: "BarbarianX DAO community platform",
    link: "https://barbarian-x-dao.vercel.app/",
    icon: "users"
  },
  {
    id: 2,
    title: "IRyS Meteor Crash",
    category: "Mini-Game",
    category_en: "Mini-Game",
    description: "Mini-game Arcade Sederhana yang dikembangkan sebagai instrumen kampanye promosi dalam proyek Web3.",
    description_en: "Simple Arcade Mini-game developed as a promotional campaign instrument in a Web3 project.",
    link: "https://irys-meteor-crash.vercel.app/",
    icon: "gamepad-2"
  },
  {
    id: 3,
    title: "Arsip Hikam",
    category: "Digital Archive",
    category_en: "Digital Archive",
    description: "Platform arsip digital dan landing page personal untuk publikasi tulisan saya.",
    description_en: "Digital archive platform and personal landing page for my writing publications.",
    link: "https://arsip-hikam.vercel.app/",
    icon: "book-open"
  },
  {
    id: 4,
    title: "Kalkulator Simulasi Investasi dan Inflasi",
    category: "Digital Tool",
    category_en: "Digital Tool",
    description: "Kalkulator untuk mensimulasikan investasi dan inflasi secara interaktif.",
    description_en: "Calculator to simulate investment and inflation interactively.",
    link: "https://kalkulator-simulasi.vercel.app/",
    icon: "calculator"
  },
  {
    id: 5,
    title: "Katalog TStore",
    category: "Website E-Commerce",
    category_en: "E-Commerce Website",
    description: "Katalog produk untuk toko product digital dengan tema Breaking Bad.",
    description_en: "Product catalog for a digital product store with a Breaking Bad theme.",
    link: "https://katalog-tstore.vercel.app/",
    icon: "shopping-bag"
  }
];

const metricsData = [
  {
    id: 101,
    title: "Memahami Scarcity: Mengapa Rencana Thanos Justru Menghancurkan Ekonomi",
    views: 4900,
    likes: 30,
    shares: 15,
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2015782815124819979?s=20"
  },
  {
    id: 102,
    title: "Suku Bajo: Penyelam Terkuat, Sang Penjelajah Samudra",
    views: 660,
    likes: 0,
    shares: 0,
    type: 'article',
    link: "https://www.kompasiana.com/hiiikam/647700a408a8b50524357193/suku-bajo-penyelam-terkuat-sang-penjelajah-samudra"
  },
  {
    id: 103,
    title: "Kemunculan Oarfish dan Mitos Bencana",
    views: 1491,
    likes: 0,
    shares: 0,
    type: 'article',
    link: "https://www.kompasiana.com/hiiikam/6419aaf44addee21a761e183/kemunculan-oarfish-dan-mitos-bencana"
  },
  {
    id: 104,
    title: "Memahami Ekonomi lewat The Last of Us",
    views: 119,
    likes: 11,
    shares: 9,
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2019439347901297057?s=20"
  },
  {
    id: 105,
    title: "Kapitalis Lu!: Mengenal Kapitalisme Lewat Ambisi Mr. Krabs",
    views: 2300,
    likes: 0,
    shares: 0,
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2020466307813036159?s=20"
  },
  {
    id: 106,
    title: "Memahami Blockchain: Menjawab Kebingungan saya dulu.",
    views: 450,
    likes: 5,
    shares: 3,
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2021225113644130507?s=20"
  },
  {
    id: 107,
    title: "Mikroekonomi: Versi Close-Up dari Dunia Ekonomi",
    views: 300,
    likes: 8,
    shares: 5,
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2023610841883701654?s=20"
  },
  {
    id: 108,
    title: "Belajar Opportunity Cost dari Tony Stark: Mengapa Iron Man Menutup Pabrik Senjatanya?",
    views: 600,
    likes: 0,
    shares: 0,
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2024149421215424674?s=20"
  },
  {
    id: 109,
    title: "Bank Run: Ketika Semua Orang Pengen \"Putus\" Sama Bank",
    views: 800,
    likes: 0,
    shares: 0,
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2025571775556591784?s=20"
  },
  {
    id: 110,
    title: "Memahami cara pak Habibie menjinakan rupiah", 
    views: 1200,
    likes: 15,
    shares: 8,
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2028097383762919794?s=20"
  },
  {
    id: 111,
    title: "Memahami Civil War: Ketika Pahlawan Berbentaran Karna Prinsip",
    views: 900,
    likes: 0,
    shares: 0,
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2030157296911708322?s=20"
  },
  {
    id: 112,
    title: "Memahami Bisnis Money Laundering Walter White dari Series Breaking Bad",
    views: 2000,
    likes: 0,
    shares: 0,  
    type: 'article',
    link: "https://x.com/0xRahvanaa/status/2032810272940040560?s=20"
  }
];
