const translations = {
    id: {
        nav_home:       "Beranda",
        nav_about:      "Tentang",
        nav_projects:   "Proyek",
        nav_articles:   "Artikel",
        nav_contact:    "Kontak",
        hero_badge:     "Merangkai Ide, Merangkul Transformasi",
        hero_role_prefix: "Seorang",
        hero_desc:      "Suka explorasi teknologi, ekonomi, dan hal-hal baru.",
        btn_projects:   "Lihat Proyek",
        btn_contact:    "Hubungi Saya",
        about_label:    "Tentang Saya",
        about_title:    `Halo, saya<span class="ta"> Muhammad Aklilul Hikam</span>`,
        about_p1:       `Saya mahasiswa <strong>Sistem Informasi Bisnis</strong> di Politeknik Negeri Malang, individu yang selalu penasaran dengan pertemuan antara teknologi dan strategi bisnis modern.`,
        about_p2:       "Perjalanan saya dimulai dari pengembangan web, lalu berkembang ke ekosistem Web3 dan Cryptocurrency. Berawal dari eksplorasi airdrop, saya menemukan minat mendalam pada teknologi blockchain dan bagaimana desentralisasi dapat mengubah masa depan ekonomi digital.",
        info_name:      "Nama Lengkap",
        info_loc:       "Lokasi",
        info_study:     "Studi",
        info_email:     "Email",
        abilities_title:"Abilities",
        ability_sleep:  "Tidur",
        ability_learn:  "Belajar Hal Baru",
        ability_idea:   "Mewujudkan Ide",
        ability_coffee: "Ngopi",
        ability_write:  "Nulis",
        projects_label: "Proyek",
        projects_title: "CASE STUDY",
        projects_subtitle:"Arsip kontribusi dan eksperimen digital",
        articles_label: "Tulisan",
        articles_title: `Apa yang <span class="ta">Saya Tulis</span>`,
        articles_subtitle:"Kumpulan tulisan dan opini tentang teknologi &amp; ekonomi",
        contact_hi:     "Say Hi!",
        contact_and:    " dan ceritakan tentang",
        contact_idea:   "idemu",
        contact_desc:   "Terbuka untuk diskusi Web3, Blockchain, atau peluang kolaborasi teknis lainnya.",
        form_name_label:"Nama",
        form_email_label:"Email",
        form_purpose_label:"Keperluan?",
        form_msg_label: "Pesan",
        form_name_ph:   "Halo...",
        form_email_ph:  "Balas ke mana?",
        form_purpose_ph:"Tulis keperluanmu disini",
        form_msg:       "Ceritakan idemu...",
        form_btn:       "Kirim pesan",
        form_sending:   "Mengirim...",
        form_sent:      "Terkirim",
        form_fail:      "Gagal Kirim",
        open_project:   "BUKA PROYEK",
        footer:         "© 2026 Muhammad Aklilul Hikam. All rights reserved.",
        roles:          ["Web3 Enthusiast", "Mahasiswa", "Penjelajah Teknologi", "Content Writer"]
    },
    en: {
        nav_home:       "Home",
        nav_about:      "About",
        nav_projects:   "Projects",
        nav_articles:   "Articles",
        nav_contact:    "Contact",
        hero_badge:     "Crafting Ideas, Embracing Transformation",
        hero_role_prefix: "A",
        hero_desc:      "Exploring technology, economics, and new things.",
        btn_projects:   "View Projects",
        btn_contact:    "Contact Me",
        about_label:    "About Me",
        about_title:    `Hi, I'm <span class="ta"> Muhammad Aklilul Hikam</span>`,
        about_p1:       `I'm a <strong>Business Information Systems</strong> student at State Polytechnic of Malang, always curious about the intersection of technology and modern business strategy.`,
        about_p2:       "My journey started with web development, then evolved into the Web3 and Cryptocurrency ecosystem. Starting from airdrop exploration, I discovered a deep interest in blockchain technology and how decentralization can reshape the future of the digital economy.",
        info_name:      "Full Name",
        info_loc:       "Location",
        info_study:     "Study",
        info_email:     "Email",
        abilities_title:"Abilities",
        ability_sleep:  "Sleeping",
        ability_learn:  "Learning New Things",
        ability_idea:   "Realizing Ideas",
        ability_coffee: "Drinking Coffee",
        ability_write:  "Writing",
        projects_label: "Projects",
        projects_title: "CASE STUDY",
        projects_subtitle:"Archive of digital contributions and experiments",
        articles_label: "Writing",
        articles_title: `What I <span class="ta">Write</span>`,
        articles_subtitle:"Collection of writings and opinions on technology &amp; economics",
        contact_hi:     "Say Hi!",
        contact_and:    " and tell me about",
        contact_idea:   "your idea",
        contact_desc:   "Open to discussions on Web3 development, Blockchain research, or other technical collaboration opportunities.",
        form_name_label:"Name",
        form_email_label:"Email",
        form_purpose_label:"Purpose?",
        form_msg_label: "Message",
        form_name_ph:   "Hello...",
        form_email_ph:  "Where can I reply?",
        form_purpose_ph:"Write your purpose here",
        form_msg:       "Tell me about your idea...",
        form_btn:       "Send me your message",
        form_sending:   "Sending...",
        form_sent:      "Sent",
        form_fail:      "Failed to Send",
        open_project:   "OPEN PROJECT",
        footer:         "© 2026 Muhammad Aklilul Hikam. All rights reserved.",
        roles:          ["Web3 Enthusiast", "Student", "Tech Explorer", "Content Writer"]
    }
};

const portfolioData = [
    {
        id: 1,
        title: "BarbarianX DAO",
        category: "DAO Governance",
        category_en: "DAO Governance",
        description: "Platform komunitas BarbarianX DAO untuk tata kelola terdesentralisasi.",
        description_en: "BarbarianX DAO community platform for decentralized governance.",
        link: "https://barbarian-x-dao.vercel.app/",
        icon: "users"
    },
    {
        id: 2,
        title: "IRyS Meteor Crash",
        category: "Mini-Game",
        category_en: "Mini-Game",
        description: "Mini-game Arcade yang dikembangkan sebagai instrumen kampanye promosi dalam proyek Web3.",
        description_en: "Arcade Mini-game developed as a promotional campaign instrument in a Web3 project.",
        link: "https://irys-meteor-crash.vercel.app/",
        icon: "gamepad-2"
    },
    {
        id: 3,
        title: "Katalog TStore",
        category: "Website E-Commerce",
        category_en: "E-Commerce Website",
        description: "Katalog produk digital dengan tema Breaking Bad yang unik dan memorable.",
        description_en: "Digital product catalog with a unique and memorable Breaking Bad theme.",
        link: "https://katalog-tstore.vercel.app/",
        icon: "shopping-bag"
    },
    {
        id: 4,
        title: "Website Laboratorium",
        category: "Web App & CMS",
        category_en: "Web App & CMS",
        description: "Website laboratorium kampus dengan fitur CMS admin (CRUD) yang dibangun menggunakan database PostgreSQL. Klik untuk melihat video demo cara kerjanya.",
        description_en: "A campus laboratory website featuring an admin CMS (CRUD) built with a PostgreSQL database. Click to watch the video demo.",
        link: "https://drive.google.com/drive/folders/1ZoWEmcHafkyWTg-ZARHDWW29MXlo8_sx?usp=sharing",
        icon: "play-circle"
    }
];

const metricsData = [
    { id:101, title:"Memahami Scarcity: Mengapa Rencana Thanos Justru Menghancurkan Ekonomi", views:4900, likes:30, shares:15, link:"https://x.com/0xRahvanaa/status/2015782815124819979" },
    { id:102, title:"Suku Bajo: Penyelam Terkuat, Sang Penjelajah Samudra", views:660, likes:20, shares:4, link:"https://www.kompasiana.com/hiiikam/647700a408a8b50524357193/suku-bajo-penyelam-terkuat-sang-penjelajah-samudra" },
    { id:103, title:"Kemunculan Oarfish dan Mitos Bencana", views:1491, likes:15, shares:2, link:"https://www.kompasiana.com/hiiikam/6419aaf44addee21a761e183/kemunculan-oarfish-dan-mitos-bencana" },
    { id:104, title:"Memahami Ekonomi lewat The Last of Us", views:119, likes:11, shares:9, link:"https://x.com/0xRahvanaa/status/2019439347901297057" },
    { id:105, title:"Kapitalis Lu!: Mengenal Kapitalisme Lewat Ambisi Mr. Krabs", views:2300, likes:20, shares:1, link:"https://x.com/0xRahvanaa/status/2020466307813036159" },
    { id:106, title:"Memahami Blockchain: Menjawab Kebingungan Saya Dulu", views:450, likes:5, shares:3, link:"https://x.com/0xRahvanaa/status/2021225113644130507" },
    { id:107, title:"Mikroekonomi: Versi Close-Up dari Dunia Ekonomi", views:300, likes:8, shares:5, link:"https://x.com/0xRahvanaa/status/2023610841883701654" },
    { id:108, title:"Belajar Opportunity Cost dari Tony Stark: Mengapa Iron Man Menutup Pabrik Senjatanya?", views:600, likes:4, shares:1, link:"https://x.com/0xRahvanaa/status/2024149421215424674" },
    { id:109, title:"Bank Run: Ketika Semua Orang Pengen Putus Sama Bank", views:800, likes:3, shares:3, link:"https://x.com/0xRahvanaa/status/2025571775556591784" },
    { id:110, title:"Memahami Cara Pak Habibie Menjinakkan Rupiah", views:1200, likes:15, shares:8, link:"https://x.com/0xRahvanaa/status/2028097383762919794" },
    { id:111, title:"Memahami Civil War: Ketika Pahlawan Berseteru Karena Prinsip", views:900, likes:11, shares:1, link:"https://x.com/0xRahvanaa/status/2030157296911708322" },
    { id:112, title:"Memahami Bisnis Money Laundering Walter White dari Breaking Bad", views:2000, likes:12, shares:1, link:"https://x.com/0xRahvanaa/status/2032810272940040560" }
];
